### ISSUE TITLE
CLI lacks HTTP basic-auth support

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/ota-tuf#162]
The garage-push command in aktualizr allows for a credentials.zip file that uses HTTP basic-auth as defined treehub.json. However, the garage-sign command in this project only supports the AuthPlusClient and does not parse treehub.json's "basic_auth" config option.

**Comment by simao** [comment]
basic auth is currently not supported by ota-tuf server. The credentials in that file for basic_auth are used by garage-push only and not garage-sign.

**Comment by doanac** [comment]
Is basic_auth on the roadmap or is this going to be a "wont-fix"?

**Comment by simao** [comment]
Sorry, this is currently not on the road map
